spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    password: Ting1994!
    username: vander
    url: jdbc:mysql://192.168.118.168:3306/shoppingMall
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server.port: 8180

dubbo:
  application:
    name: shopping_mall_shop_web
  registry:
    address: zookeeper://192.168.118.168:2181
  consumer:
    timeout: 3000

logging:
  level:
    org.springframework.security: INFO